const {Router} = require("express")
const resumeController = require("../controllers/resumeController")
const router = Router()

router.post("/api/resume", resumeController.details)
router.get("/api/getdetails/:id", resumeController.getdetails)
router.get("/api/getdetailsall", resumeController.getdetailsall)
router.get("/api/getprofileviews", resumeController.getprofileviews)
router.post("/api/incprofileviews/:id", resumeController.incprofileviews)
router.get("/api/getdevelopers", resumeController.getdevelopers)
router.get("/api/getdesigners", resumeController.getdesigners)
router.get("/api/getdatascientist", resumeController.getdatascientist)
router.get("/api/getbusinessanalyst", resumeController.getbusinessaanalyst)
router.get("/api/getaiandml", resumeController.getalandml)
router.get("/api/getcloud", resumeController.getcloud)
router.get("/api/getdevops", resumeController.getdevops)
router.get("/api/getblockchain", resumeController.getblokchain)
router.get("/api/getreact", resumeController.getreact)
router.get("/api/filterprofiles/:filter", resumeController.filterprofiles)
router.put("/api/updateresume/:id", resumeController.updateresume)
router.post("/api/sendmail", resumeController.sendemail)
module.exports = router;